package com.dronepeak.app

enum class AppLanguage(val prefValue: String, val flag: String, val shortName: String) {
    TR("tr", "🇹🇷", "TR"),
    EN("en", "🇬🇧", "EN");

    companion object {
        fun fromPref(value: String?): AppLanguage =
            entries.firstOrNull { it.prefValue == value } ?: TR
    }
}

data class UiText(
    val updateAvailableTitle: (String) -> String,
    val updateAvailableDetail: String,
    val link: String,
    val region: String,
    val keep: String,
    val on: String,
    val off: String,
    val controller: String,
    val unknown: String,
    val aircraftSerial: String,
    val notDetected: String,
    val operation: String,
    val refreshSerial: String,
    val fccControl: String,
    val working: String,
    val connectHint: String,
    val connect: String,
    val fccActiveHint: String,
    val stopFcc: String,
    val reapply: String,
    val readyApplyFcc: String,
    val enableFcc: String,
    val keepaliveActive: String,
    val keepaliveInactive: String,
    val aircraftUtilities: String,
    val fourGHint: String,
    val sending4g: String,
    val send4g: String,
    val externalLed: String,
    val statusPrefix: String,
    val ledRequiresDji: String,
    val ledOn: String,
    val ledOff: String,
    val autoFccDetail: String,
    val deviceInfo: String,
    val connection: String,
    val status: String,
    val connected: String,
    val disconnected: String,
    val version: String,
    val query: String,
    val connectFirst: String,
    val queryVersionHint: String,
    val activityLog: String,
    val noActivity: String,
    val updates: String,
    val checkingLatest: String,
    val updateCheckFailed: String,
    val retry: String,
    val upstreamUpdateAvailable: String,
    val upToDate: String,
    val currentVersion: (String) -> String,
    val latest: String,
    val released: String,
    val size: String,
    val changelog: String,
    val noChangelog: String,
    val dronePeakBuildRequired: String,
    val upstreamApkBlocked: String,
    val profileUpdateAvailable: String,
    val applyProfileUpdate: String,
    val downloadDronePeakUpdate: String,
    val installDronePeakUpdate: String,
    val downloadingDronePeakUpdate: String,
    val updateReadyToInstall: String,
    val installPermissionRequired: String,
    val openInstallSettings: String,
    val installerOpen: String,
    val retryInstallation: String,
    val cancelDownload: String,
    val updateCancelled: String,
    val updateDownloadFailed: String,
    val updateVerificationFailed: String,
    val installerUnavailable: String,
    val updateDiagnostics: String,
    val preparingInstallation: String,
    val waitingForAndroidApproval: String,
    val installationCompleted: String,
    val applyingProfileUpdate: String,
    val profileUpdateApplied: String,
    val checkAgain: String,
    val rcPanel: String,
    val fcc: String,
    val info: String,
    val log: String,
    val update: String,
    val language: String,
    val online: String,
    val offline: String,
    val linking: String,
    val error: String,
    val hardwareBusy: String,
    val fourGBusy: String,
    val ledBusy: String,
    val ready: String,
    val hardware: String,
    val bootloader: String,
    val firmware: String,
    val rawPayload: (Int) -> String,

    // --- Redesign: control-page structure, blocked reasons, manual serial ---
    val control: String,
    val utilities: String,
    val aircraftLink: String,
    val manualSerial: String,
    val manualSerialHint: String,
    val useManualSerial: String,
    val clearManualSerial: String,
    val serialIsManual: String,
    val blockedBusy: String,
    val blockedNeedLink: String,
    val blockedNeedSerial: String,
    val blockedNeedAircraft: String,
    val keepaliveConflicts4g: String,
    val fourGUnverified: String,
    val detectedSerial: String,
    val reapplyFcc: String,
    val brand: String,
    val regionUnknown: String,
    val droneIllustration: String,
    val fccWriteNote: String,
    val stopShort: String,
    val fourGShort: String,
    val djiFly: String,
    val autoFcc: String,
    val keepalive: String,
    val infoSubtitle: String,
    val logSubtitle: String,
    val updateSubtitle: String,
    val sourceAndLicense: String,
    val sourceGithub: String,
    val license: String,
    val redownload: String,
    val browserUnavailable: String
)

object TextCatalog {
    /** Presentation-only localization; protocol messages and decisions stay upstream. */
    fun operationMessage(raw: String, language: AppLanguage): String {
        if (language == AppLanguage.EN) return raw
            .replace("FCC mode enabled", "FCC commands sent")
            .replace("FCC enabled. Starting keepalive...", "FCC commands sent. Starting keepalive...")
            .replace("FCC active. Launching DJI Fly...", "FCC commands sent. Launching DJI Fly...")
            .replace("CE mode restored", "CE commands sent")
        if (raw == "ON") return tr.on
        if (raw == "OFF") return tr.off
        return operationTranslations.fold(raw) { value, (original, translated) ->
            value.replace(original, translated)
        }
    }

    private val operationTranslations = listOf(
        " isn't in the known-4G list, but a dongle check follows — trying anyway. If 4G doesn't activate, this aircraft may not accept the Cellular Dongle 2." to " bilinen 4G listesinde yok; dongle kontrol edilerek yine de denenecek. Bu hava aracı Cellular Dongle 2’yi desteklemiyor olabilir.",
        "4G dongle not detected. Connect a DJI Cellular Dongle 2 to the aircraft (Mini 4 Pro also needs its 4G mounting kit) and try again." to "4G dongle algılanmadı. Hava aracına DJI Cellular Dongle 2 bağlayıp tekrar dene (Mini 4 Pro için 4G montaj kiti de gerekir).",
        "No serial detected — power on and link the aircraft with the live view up, or enter it manually." to "Seri bulunamadı — hava aracını açıp canlı görüntüyle bağla veya seriyi elle gir.",
        "4G activation failed — no aircraft serial detected; power on the drone and tap Connect first" to "4G gönderimi başarısız — seri numarası bulunamadı; drone’u açıp Bağlan’a bas",
        "4G needs the aircraft connected. Power on the drone, link it, and tap Connect first." to "4G için hava aracı bağlantısı gerekiyor. Drone’u aç, kumandayla eşleştir ve Bağlan’a bas.",
        "4G activation aborted — 4G socket /duss/mb/0x205 not connectable (no dongle?)" to "4G gönderimi durduruldu — /duss/mb/0x205 soketine bağlanılamadı (dongle bağlı mı?)",
        "All activation frames written successfully — check 4G status on the aircraft." to "Tüm aktivasyon frameleri yazıldı — 4G durumunu hava aracından kontrol et.",
        "FCC apply failed — RC link unreachable. Make sure the drone is on and linked." to "FCC gönderimi başarısız — kumanda bağlantısına ulaşılamıyor. Drone açık ve bağlı olmalı.",
        "4G activation failed — at least one frame write failed on the Unix socket" to "4G gönderimi başarısız — Unix soketindeki en az bir yazma başarısız oldu",
        "LED command failed — make sure DJI Fly is running with aircraft connected" to "LED komutu başarısız — DJI Fly açık ve hava aracı bağlı olmalı",
        "No reply to the serial query — listening for telemetry (up to 8s)..." to "Seri sorgusuna yanıt yok — telemetri dinleniyor (en fazla 8 saniye)...",
        "Controller not found. Make sure the drone is powered on and linked." to "Kumanda bulunamadı. Drone’un açık ve kumandayla eşleşmiş olduğundan emin ol.",
        "Auto-FCC skipped — another hardware operation is already running" to "Auto-FCC atlandı — başka bir donanım işlemi sürüyor",
        "Hardware busy — please wait for the current operation to finish." to "Donanım meşgul — mevcut işlemin bitmesini bekle.",
        "Started FCC keepalive — re-applying every 2s to prevent CE reset" to "FCC Keepalive başladı — 2 saniyede bir tekrar uygulanıyor",
        "Controller not found. Auto-FCC will retry when you tap Connect." to "Kumanda bulunamadı. Bağlan’a bastığında tekrar deneyebilirsin.",
        "Auto-FCC: controller not found — is the drone powered on?" to "Auto-FCC: kumanda bulunamadı — drone açık mı?",
        "DJI Fly not installed or cannot launch on this controller" to "DJI Fly bu kumandada yüklü değil veya açılamıyor",
        "Auto-FCC enabled — will auto-connect on next launch" to "Auto-FCC açıldı — sonraki açılışta otomatik bağlanacak",
        "Manual serial cleared — auto-detection will be used" to "Elle girilen seri temizlendi — otomatik algılama kullanılacak",
        "Auto-FCC: keepalive started (re-applying every 2s)" to "Auto-FCC: Keepalive başladı (2 saniyede bir tekrar uygulanıyor)",
        "4G apply failed — is the 4G dongle connected?" to "4G gönderimi başarısız — 4G dongle bağlı mı?",
        "Auto-FCC enabled — connecting and applying..." to "Auto-FCC açık — bağlanıyor ve uygulanıyor...",
        "Connection failed — is the drone powered on?" to "Bağlantı başarısız — drone açık mı?",
        " frames written successfully via Unix socket" to " frame Unix soketine yazıldı",
        "CE restore failed — RC link unreachable" to "CE gönderimi başarısız — kumandaya ulaşılamıyor",
        "Auto-FCC: apply failed — try manually" to "Auto-FCC: gönderim başarısız — manuel dene",
        "FCC enabled. Starting keepalive..." to "FCC komutları gönderildi. Keepalive başlatılıyor...",
        "Device info: profile has no frames" to "Cihaz bilgisi: profilde frame yok",
        "FCC apply failed — writes failed" to "FCC gönderimi başarısız — frameler yazılamadı",
        "FCC active. Launching DJI Fly..." to "FCC komutları gönderildi. DJI Fly açılıyor...",
        "Connected. Auto-applying FCC..." to "Bağlandı. FCC otomatik uygulanıyor...",
        "Connect to the controller first" to "Önce kumandayı bağla",
        "Sending 4G activation frames..." to "4G aktivasyon frameleri gönderiliyor...",
        "Auto-FCC: controller connected" to "Auto-FCC: kumanda bağlandı",
        "Auto-FCC: applying FCC mode..." to "Auto-FCC: FCC komutları gönderiliyor...",
        "Auto-FCC failed — try manually" to "Auto-FCC başarısız — manuel dene",
        "Connected. Ready to apply FCC." to "Bağlandı. FCC komutlarını göndermeye hazır.",
        "Failed — is DJI Fly running?" to "Başarısız — DJI Fly açık mı?",
        "Auto-FCC: launching DJI Fly" to "Auto-FCC: DJI Fly açılıyor",
        "Connecting to controller..." to "Kumandaya bağlanılıyor...",
        "No response from controller" to "Kumandadan yanıt alınamadı",
        "Reading aircraft serial..." to "Hava aracı seri numarası okunuyor...",
        "Keepalive already running" to "Keepalive zaten çalışıyor",
        "device_info.json is empty" to "device_info.json boş",
        "Device info: no response" to "Cihaz bilgisi: yanıt yok",
        "LED busy — please wait." to "LED işlemi sürüyor — bekle.",
        "Querying device info..." to "Cihaz bilgisi sorgulanıyor...",
        " (note: unusual format)" to " (not: alışılmadık biçim)",
        "Language set to English" to "Dil İngilizce olarak ayarlandı",
        "Device info received: " to "Cihaz bilgisi alındı: ",
        "FCC keepalive stopped" to "FCC Keepalive durduruldu",
        "4G activation error: " to "4G gönderim hatası: ",
        "Controller connected" to "Kumanda bağlandı",
        "Enabling FCC mode..." to "FCC komutları gönderiliyor...",
        "Applying FCC mode..." to "FCC komutları gönderiliyor...",
        "Restoring CE mode..." to "CE komutları gönderiliyor...",
        "DUML port detected: " to "DUML portu algılandı: ",
        "Loaded FCC profile: " to "FCC profili yüklendi: ",
        "Loaded LED profile: " to "LED profili yüklendi: ",
        "Turning LEDs off..." to "LED kapatılıyor...",
        "Manual serial set: " to "Elle girilen seri: ",
        "Device info error: " to "Cihaz bilgisi hatası: ",
        "Loaded 4G profile: " to "4G profili yüklendi: ",
        "4G activation: all " to "4G gönderimi: toplam ",
        "Turning LEDs on..." to "LED açılıyor...",
        "CE restore error: " to "CE gönderim hatası: ",
        "Auto-connecting..." to "Otomatik bağlanıyor...",
        "Auto-FCC disabled" to "Auto-FCC kapatıldı",
        "CE restore failed" to "CE gönderimi başarısız",
        "Launched DJI Go 4" to "DJI Go 4 açıldı",
        "Aircraft serial: " to "Hava aracı seri numarası: ",
        "FCC apply error: " to "FCC gönderim hatası: ",
        " frames (serial: " to " frame (seri: ",
        "CE mode restored" to "CE komutları gönderildi",
        "FCC mode enabled" to "FCC komutları gönderildi",
        "Launched DJI Fly" to "DJI Fly açıldı",
        "Auto-FCC error: " to "Auto-FCC hatası: ",
        "LEDs turned off" to "LED kapatma komutları gönderildi",
        "LEDs turned on" to "LED açma komutları gönderildi",
        " frames (port " to " frame (port ",
        "Raw payload (" to "Ham veri (",
        "Connected — " to "Bağlandı — ",
        " frames sent" to " frame gönderildi",
        "Note: model " to "Not: model ",
        "LED error: " to "LED hatası: ",
        "4G error: " to "4G hatası: ",
        "Hardware: " to "Donanım: ",
        "Firmware: " to "Firmware: ",
        " (cached)" to " (kaydedildi)",
        " frames, " to " frame, ",
        ", model: " to ", model: ",
        " bytes):" to " bayt):",
        "Error: " to "Hata: ",
        " rounds" to " tur",
        " bytes" to " bayt",
    )

    fun ui(language: AppLanguage): UiText = when (language) {
        AppLanguage.TR -> tr
        AppLanguage.EN -> en
    }

    private val tr = UiText(
        updateAvailableTitle = { "DronePeak-FCC v$it hazır" },
        updateAvailableDetail = "Yeni sürümü indirmek için Güncelle sekmesini aç.",
        link = "BAĞ",
        region = "BÖLGE",
        keep = "KORU",
        on = "AÇIK",
        off = "KAPALI",
        controller = "Kumanda",
        unknown = "Bilinmiyor",
        aircraftSerial = "Hava aracı S/N",
        notDetected = "Algılanmadı",
        operation = "İşlem",
        refreshSerial = "Seri numarasını yenile",
        fccControl = "FCC Kontrol",
        working = "İşleniyor...",
        connectHint = "Hava aracını açıp kumandaya bağla, sonra bağlantıyı başlat.",
        connect = "Bağlan",
        fccActiveHint = "FCC komutları gönderildi. Keepalive komutları tekrar uygulayabilir.",
        stopFcc = "FCC Modunu Durdur",
        reapply = "Tekrar Uygula",
        readyApplyFcc = "FCC modunu uygulamaya hazır.",
        enableFcc = "FCC Modunu Aç",
        keepaliveActive = "FCC her 2 saniyede tekrar uygulanıyor",
        keepaliveInactive = "DJI Fly çalışırken FCC modunu koru",
        aircraftUtilities = "Hava Aracı Araçları",
        fourGHint = "4G sadece aktivasyon framelerini yazar; sonucu DJI Fly veya dongle üzerinden kontrol et.",
        sending4g = "4G aktivasyon frameleri gönderiliyor",
        send4g = "4G Aktivasyon Gönder",
        externalLed = "Harici LED",
        statusPrefix = "Durum",
        ledRequiresDji = "DJI Fly açık ve hava aracı bağlı olmalı",
        ledOn = "LED AÇ",
        ledOff = "LED KAPAT",
        autoFccDetail = "Otomatik bağlan, FCC uygula, Keepalive başlat, DJI Fly aç",
        deviceInfo = "Cihaz Bilgisi",
        connection = "Bağlantı",
        status = "Durum",
        connected = "Bağlı",
        disconnected = "Bağlı değil",
        version = "Sürüm",
        query = "Sorgula",
        connectFirst = "Önce kumandaya bağlan.",
        queryVersionHint = "Donanım ve firmware bilgisini sorgulamak için yenilemeye bas.",
        activityLog = "İşlem Günlüğü",
        noActivity = "Henüz işlem yok.",
        updates = "Güncellemeler",
        checkingLatest = "DronePeak-FCC güncellemeleri kontrol ediliyor",
        updateCheckFailed = "Güncelleme kontrol edilemedi.",
        retry = "Tekrar dene",
        upstreamUpdateAvailable = "Yeni Sürüm Hazır",
        upToDate = "Güncel",
        currentVersion = { "Mevcut v$it" },
        latest = "Son sürüm",
        released = "Yayın tarihi",
        size = "Boyut",
        changelog = "Değişiklikler",
        noChangelog = "Değişiklik notu yok.",
        dronePeakBuildRequired = "DronePeak-FCC güncellemesi hazır.",
        upstreamApkBlocked = "İndirme tamamlanınca kurulumu başlatabilirsin.",
        profileUpdateAvailable = "Profil dosyaları uygulama ile birlikte güncellenir.",
        applyProfileUpdate = "Profil Güncelle",
        downloadDronePeakUpdate = "Güncellemeyi İndir",
        installDronePeakUpdate = "Güncellemeyi Kur",
        downloadingDronePeakUpdate = "Güncelleme indiriliyor",
        updateReadyToInstall = "Güncelleme indirildi. Kuruluma hazır.",
        installPermissionRequired = "Kurulumu başlatmak için Android ayarlarından DronePeak-FCC'ye uygulama yükleme izni ver.",
        openInstallSettings = "Kurulum İznini Aç",
        installerOpen = "Android kurulum ekranı açık. Kurulum iptal edilirse buraya dönüp tekrar deneyebilirsin.",
        retryInstallation = "Kurulumu Tekrar Aç",
        cancelDownload = "İndirmeyi İptal Et",
        updateCancelled = "Güncelleme indirmesi iptal edildi.",
        updateDownloadFailed = "Güncelleme indirilemedi. Bağlantını ve boş depolama alanını kontrol et.",
        updateVerificationFailed = "İndirilen güncelleme doğrulanamadı. Güvenlik için kuruluma izin verilmedi.",
        installerUnavailable = "Bu kumandada Android kurulum ekranı açılamadı.",
        updateDiagnostics = "Son Güncelleme Raporu",
        preparingInstallation = "Kurulum hazırlanıyor...",
        waitingForAndroidApproval = "Android kurulum onayı bekleniyor.",
        installationCompleted = "Güncelleme tamamlandı.",
        applyingProfileUpdate = "Profiller uygulanıyor",
        profileUpdateApplied = "Profil güncellemesi uygulandı",
        checkAgain = "Tekrar kontrol et",
        rcPanel = "RC PANEL",
        fcc = "FCC",
        info = "Bilgi",
        log = "Günlük",
        update = "Güncelle",
        language = "Dil",
        online = "ONLINE",
        offline = "OFFLINE",
        linking = "BAĞLANIYOR",
        error = "HATA",
        hardwareBusy = "Donanım meşgul",
        fourGBusy = "4G meşgul",
        ledBusy = "LED meşgul",
        ready = "Hazır",
        hardware = "Donanım",
        bootloader = "Bootloader",
        firmware = "Firmware",
        rawPayload = { "Ham veri ($it bayt):" },
        control = "Kontrol",
        utilities = "Araçlar",
        aircraftLink = "Bağlantı",
        manualSerial = "Hava aracı seri numarası",
        manualSerialHint = "Kumanda seri okuyamıyorsa elle gir. Elle girilen seri tüm otomatik algılamayı geçer.",
        useManualSerial = "Bu seriyi kullan",
        clearManualSerial = "Elle girdiği seriyi temizle",
        serialIsManual = "Elle girildi",
        blockedBusy = "Başka bir donanım işlemi sürüyor",
        blockedNeedLink = "Önce kumandayı bağla",
        blockedNeedSerial = "Hava aracı seri numarası gerekli",
        blockedNeedAircraft = "Hava aracı açık ve link olmalı",
        keepaliveConflicts4g = "Keepalive her 2 saniyede bir FCC yeniden uyguluyor ve 4G aktivasyonunu geçersiz kılabilir.",
        fourGUnverified = "4G soketi yanıt vermez; yazma tamamlandı, hava aracından doğrula.",
        detectedSerial = "Okunan seri",
        reapplyFcc = "Yeniden uygula",
        brand = "DronePeak",
        regionUnknown = "—",
        droneIllustration = "Temsili drone görseli",
        fccWriteNote = "FCC/CE durumu gönderilen komutu gösterir; hava aracı onayı değildir.",
        stopShort = "CE’ye dön",
        fourGShort = "4G gönder",
        djiFly = "DJI Fly",
        autoFcc = "Auto-FCC",
        keepalive = "Keepalive",
        infoSubtitle = "Kumanda bilgileri ve hava aracı seri numarası.",
        logSubtitle = "Son işlemler · en yeni kayıt üstte.",
        updateSubtitle = "DronePeak uygulaması ve FreeFCC komut profilleri.",
        sourceAndLicense = "Kaynak ve lisans",
        sourceGithub = "DronePeak kaynak kodu",
        license = "Lisans",
        redownload = "Yeniden indir",
        browserUnavailable = "Bu kumandada bağlantıyı açabilecek bir tarayıcı yok."
    )

    private val en = UiText(
        updateAvailableTitle = { "DronePeak-FCC v$it ready" },
        updateAvailableDetail = "Open the Update tab to download the new version.",
        link = "LINK",
        region = "REGION",
        keep = "KEEP",
        on = "ON",
        off = "OFF",
        controller = "Controller",
        unknown = "Unknown",
        aircraftSerial = "Aircraft S/N",
        notDetected = "Not detected",
        operation = "Operation",
        refreshSerial = "Refresh serial",
        fccControl = "FCC Control",
        working = "Working...",
        connectHint = "Power on and link the aircraft, then connect to the controller.",
        connect = "Connect",
        fccActiveHint = "FCC commands were sent. Keepalive can re-apply the commands.",
        stopFcc = "Stop FCC Mode",
        reapply = "Re-Apply",
        readyApplyFcc = "Ready to apply FCC mode.",
        enableFcc = "Enable FCC Mode",
        keepaliveActive = "Re-applying FCC every 2s",
        keepaliveInactive = "Maintain FCC while DJI Fly runs",
        aircraftUtilities = "Aircraft Utilities",
        fourGHint = "4G writes activation frames only; confirm final status in DJI Fly or on the dongle.",
        sending4g = "Sending 4G activation frames",
        send4g = "Send 4G Activation",
        externalLed = "External LED",
        statusPrefix = "Status",
        ledRequiresDji = "Requires DJI Fly with aircraft connected",
        ledOn = "LED ON",
        ledOff = "LED OFF",
        autoFccDetail = "Auto-connect, apply FCC, start keepalive, launch DJI Fly",
        deviceInfo = "Device Info",
        connection = "Connection",
        status = "Status",
        connected = "Connected",
        disconnected = "Disconnected",
        version = "Version",
        query = "Query",
        connectFirst = "Connect to the controller first.",
        queryVersionHint = "Tap refresh to query hardware and firmware info.",
        activityLog = "Activity Log",
        noActivity = "No activity yet.",
        updates = "Updates",
        checkingLatest = "Checking DronePeak-FCC updates",
        updateCheckFailed = "Could not check for updates.",
        retry = "Retry",
        upstreamUpdateAvailable = "New Version Ready",
        upToDate = "Up to Date",
        currentVersion = { "Current v$it" },
        latest = "Latest version",
        released = "Released",
        size = "Size",
        changelog = "Changelog",
        noChangelog = "No changelog provided.",
        dronePeakBuildRequired = "DronePeak-FCC update is ready.",
        upstreamApkBlocked = "Start installation after the download completes.",
        profileUpdateAvailable = "Profile files update together with the app.",
        applyProfileUpdate = "Update Profiles",
        downloadDronePeakUpdate = "Download Update",
        installDronePeakUpdate = "Install Update",
        downloadingDronePeakUpdate = "Downloading update",
        updateReadyToInstall = "Update downloaded. Ready to install.",
        installPermissionRequired = "To start installation, allow DronePeak-FCC to install apps in Android settings.",
        openInstallSettings = "Open Install Permission",
        installerOpen = "The Android installer is open. If installation is cancelled, return here and try again.",
        retryInstallation = "Open Installer Again",
        cancelDownload = "Cancel Download",
        updateCancelled = "Update download cancelled.",
        updateDownloadFailed = "Could not download the update. Check the connection and free storage.",
        updateVerificationFailed = "The downloaded update could not be verified. Installation was blocked for safety.",
        installerUnavailable = "The Android installer could not be opened on this controller.",
        updateDiagnostics = "Latest Update Report",
        preparingInstallation = "Preparing installation...",
        waitingForAndroidApproval = "Waiting for Android install approval.",
        installationCompleted = "Update completed.",
        applyingProfileUpdate = "Applying profiles",
        profileUpdateApplied = "Profile update applied",
        checkAgain = "Check Again",
        rcPanel = "RC PANEL",
        fcc = "FCC",
        info = "Info",
        log = "Log",
        update = "Update",
        language = "Language",
        online = "ONLINE",
        offline = "OFFLINE",
        linking = "LINKING",
        error = "ERROR",
        hardwareBusy = "Hardware busy",
        fourGBusy = "4G busy",
        ledBusy = "LED busy",
        ready = "Ready",
        hardware = "Hardware",
        bootloader = "Bootloader",
        firmware = "Firmware",
        rawPayload = { "Raw payload ($it bytes):" },
        control = "Control",
        utilities = "Utilities",
        aircraftLink = "Link",
        manualSerial = "Aircraft serial",
        manualSerialHint = "Type it here when the controller cannot report a serial. A manual serial wins over every detected value.",
        useManualSerial = "Use this serial",
        clearManualSerial = "Clear manual serial",
        serialIsManual = "Manual",
        blockedBusy = "Another hardware operation is running",
        blockedNeedLink = "Connect the controller first",
        blockedNeedSerial = "Aircraft serial required",
        blockedNeedAircraft = "Aircraft must be on and linked",
        keepaliveConflicts4g = "Keepalive re-applies FCC every 2s and can undo the 4G activation.",
        fourGUnverified = "The 4G socket never acknowledges; the write finished, so confirm it on the aircraft.",
        detectedSerial = "Detected serial",
        reapplyFcc = "Reapply",
        brand = "DronePeak",
        regionUnknown = "—",
        droneIllustration = "Illustrative aircraft",
        fccWriteNote = "FCC/CE shows the command sent, not aircraft confirmation.",
        stopShort = "Restore CE",
        fourGShort = "Send 4G",
        djiFly = "DJI Fly",
        autoFcc = "Auto-FCC",
        keepalive = "Keepalive",
        infoSubtitle = "Controller details and aircraft serial number.",
        logSubtitle = "Recent operations · newest first.",
        updateSubtitle = "DronePeak application and FreeFCC command profiles.",
        sourceAndLicense = "Source and license",
        sourceGithub = "DronePeak source code",
        license = "License",
        redownload = "Download again",
        browserUnavailable = "No browser is available to open this link on the controller."
    )
}
