package com.dronepeak.app

enum class AppLanguage(val prefValue: String, val flag: String, val shortName: String) {
    TR("tr", "🇹🇷", "TR"),
    EN("en", "🇬🇧", "EN");

    companion object {
        fun fromPref(value: String?): AppLanguage =
            entries.firstOrNull { it.prefValue == value } ?: TR
    }
}

data class UiText(
    val updateAvailableTitle: (String) -> String,
    val updateAvailableDetail: String,
    val link: String,
    val region: String,
    val keep: String,
    val on: String,
    val off: String,
    val controller: String,
    val unknown: String,
    val aircraftSerial: String,
    val notDetected: String,
    val operation: String,
    val refreshSerial: String,
    val fccControl: String,
    val working: String,
    val connectHint: String,
    val connect: String,
    val fccActiveHint: String,
    val stopFcc: String,
    val reapply: String,
    val readyApplyFcc: String,
    val enableFcc: String,
    val keepaliveActive: String,
    val keepaliveInactive: String,
    val aircraftUtilities: String,
    val fourGHint: String,
    val sending4g: String,
    val send4g: String,
    val externalLed: String,
    val statusPrefix: String,
    val ledRequiresDji: String,
    val ledOn: String,
    val ledOff: String,
    val autoFccDetail: String,
    val deviceInfo: String,
    val connection: String,
    val status: String,
    val connected: String,
    val disconnected: String,
    val version: String,
    val query: String,
    val connectFirst: String,
    val queryVersionHint: String,
    val activityLog: String,
    val noActivity: String,
    val updates: String,
    val checkingLatest: String,
    val updateCheckFailed: String,
    val retry: String,
    val upstreamUpdateAvailable: String,
    val upToDate: String,
    val currentVersion: (String) -> String,
    val latest: String,
    val released: String,
    val size: String,
    val changelog: String,
    val noChangelog: String,
    val dronePeakBuildRequired: String,
    val upstreamApkBlocked: String,
    val profileUpdateAvailable: String,
    val applyProfileUpdate: String,
    val downloadDronePeakUpdate: String,
    val installDronePeakUpdate: String,
    val downloadingDronePeakUpdate: String,
    val applyingProfileUpdate: String,
    val profileUpdateApplied: String,
    val checkAgain: String,
    val rcPanel: String,
    val fcc: String,
    val info: String,
    val log: String,
    val update: String,
    val language: String,
    val online: String,
    val offline: String,
    val linking: String,
    val error: String,
    val hardwareBusy: String,
    val fourGBusy: String,
    val ledBusy: String,
    val ready: String,
    val hardware: String,
    val bootloader: String,
    val firmware: String,
    val rawPayload: (Int) -> String
)

object TextCatalog {
    fun ui(language: AppLanguage): UiText = when (language) {
        AppLanguage.TR -> tr
        AppLanguage.EN -> en
    }

    private val tr = UiText(
        updateAvailableTitle = { "DronePeak v$it mevcut" },
        updateAvailableDetail = "Bu güncelleme DronePeak release kanalından gelir",
        link = "BAĞ",
        region = "BÖLGE",
        keep = "KORU",
        on = "AÇIK",
        off = "KAPALI",
        controller = "Kumanda",
        unknown = "Bilinmiyor",
        aircraftSerial = "Hava aracı S/N",
        notDetected = "Algılanmadı",
        operation = "İşlem",
        refreshSerial = "Seri numarasını yenile",
        fccControl = "FCC Kontrol",
        working = "İşleniyor...",
        connectHint = "Hava aracını açıp kumandaya bağla, sonra bağlantıyı başlat.",
        connect = "Bağlan",
        fccActiveHint = "FCC modu aktif. DJI Fly açıkken Keepalive bu durumu koruyabilir.",
        stopFcc = "FCC Modunu Durdur",
        reapply = "Tekrar Uygula",
        readyApplyFcc = "FCC modunu uygulamaya hazır.",
        enableFcc = "FCC Modunu Aç",
        keepaliveActive = "FCC her 2 saniyede tekrar uygulanıyor",
        keepaliveInactive = "DJI Fly çalışırken FCC modunu koru",
        aircraftUtilities = "Hava Aracı Araçları",
        fourGHint = "4G sadece aktivasyon framelerini yazar; sonucu DJI Fly veya dongle üzerinden kontrol et.",
        sending4g = "4G aktivasyon frameleri gönderiliyor",
        send4g = "4G Aktivasyon Gönder",
        externalLed = "Harici LED",
        statusPrefix = "Durum",
        ledRequiresDji = "DJI Fly açık ve hava aracı bağlı olmalı",
        ledOn = "LED AÇ",
        ledOff = "LED KAPAT",
        autoFccDetail = "Otomatik bağlan, FCC uygula, Keepalive başlat, DJI Fly aç",
        deviceInfo = "Cihaz Bilgisi",
        connection = "Bağlantı",
        status = "Durum",
        connected = "Bağlı",
        disconnected = "Bağlı değil",
        version = "Sürüm",
        query = "Sorgula",
        connectFirst = "Önce kumandaya bağlan.",
        queryVersionHint = "Donanım ve firmware bilgisini sorgulamak için yenilemeye bas.",
        activityLog = "İşlem Günlüğü",
        noActivity = "Henüz işlem yok.",
        updates = "Güncellemeler",
        checkingLatest = "DronePeak GitHub release kontrol ediliyor",
        updateCheckFailed = "Güncelleme kontrol edilemedi.",
        retry = "Tekrar dene",
        upstreamUpdateAvailable = "DronePeak Güncellemesi Var",
        upToDate = "Güncel",
        currentVersion = { "Mevcut v$it" },
        latest = "Son DronePeak",
        released = "Yayın tarihi",
        size = "Boyut",
        changelog = "Değişiklikler",
        noChangelog = "Değişiklik notu yok.",
        dronePeakBuildRequired = "FreeFCC upstream kod güncellemeleri bu repo'ya kaynak seviyesinde merge edilir. Kullanıcıya yalnızca imzalı DronePeak APK yayınlanır.",
        upstreamApkBlocked = "Upstream APK kurulmaz; DronePeak APK tasarımı, ikonları ve dili korur.",
        profileUpdateAvailable = "İstersen sadece upstream DUML profil/veri dosyalarını da uygulayabilirsin.",
        applyProfileUpdate = "Upstream Profil Güncelle",
        downloadDronePeakUpdate = "DronePeak APK İndir",
        installDronePeakUpdate = "DronePeak APK Kur",
        downloadingDronePeakUpdate = "DronePeak APK indiriliyor",
        applyingProfileUpdate = "Upstream profiller uygulanıyor",
        profileUpdateApplied = "Profil güncellemesi uygulandı",
        checkAgain = "Tekrar kontrol et",
        rcPanel = "RC PANEL",
        fcc = "FCC",
        info = "Bilgi",
        log = "Günlük",
        update = "Güncelle",
        language = "Dil",
        online = "ONLINE",
        offline = "OFFLINE",
        linking = "BAĞLANIYOR",
        error = "HATA",
        hardwareBusy = "Donanım meşgul",
        fourGBusy = "4G meşgul",
        ledBusy = "LED meşgul",
        ready = "Hazır",
        hardware = "Donanım",
        bootloader = "Bootloader",
        firmware = "Firmware",
        rawPayload = { "Ham payload ($it bayt):" }
    )

    private val en = UiText(
        updateAvailableTitle = { "DronePeak v$it available" },
        updateAvailableDetail = "This update comes from the DronePeak release channel",
        link = "LINK",
        region = "REGION",
        keep = "KEEP",
        on = "ON",
        off = "OFF",
        controller = "Controller",
        unknown = "Unknown",
        aircraftSerial = "Aircraft S/N",
        notDetected = "Not detected",
        operation = "Operation",
        refreshSerial = "Refresh serial",
        fccControl = "FCC Control",
        working = "Working...",
        connectHint = "Power on and link the aircraft, then connect to the controller.",
        connect = "Connect",
        fccActiveHint = "FCC mode is active. Keepalive can maintain it while DJI Fly is running.",
        stopFcc = "Stop FCC Mode",
        reapply = "Re-Apply",
        readyApplyFcc = "Ready to apply FCC mode.",
        enableFcc = "Enable FCC Mode",
        keepaliveActive = "Re-applying FCC every 2s",
        keepaliveInactive = "Maintain FCC while DJI Fly runs",
        aircraftUtilities = "Aircraft Utilities",
        fourGHint = "4G writes activation frames only; confirm final status in DJI Fly or on the dongle.",
        sending4g = "Sending 4G activation frames",
        send4g = "Send 4G Activation",
        externalLed = "External LED",
        statusPrefix = "Status",
        ledRequiresDji = "Requires DJI Fly with aircraft connected",
        ledOn = "LED ON",
        ledOff = "LED OFF",
        autoFccDetail = "Auto-connect, apply FCC, start keepalive, launch DJI Fly",
        deviceInfo = "Device Info",
        connection = "Connection",
        status = "Status",
        connected = "Connected",
        disconnected = "Disconnected",
        version = "Version",
        query = "Query",
        connectFirst = "Connect to the controller first.",
        queryVersionHint = "Tap refresh to query hardware and firmware info.",
        activityLog = "Activity Log",
        noActivity = "No activity yet.",
        updates = "Updates",
        checkingLatest = "Checking DronePeak GitHub release",
        updateCheckFailed = "Could not check for updates.",
        retry = "Retry",
        upstreamUpdateAvailable = "DronePeak Update Available",
        upToDate = "Up to Date",
        currentVersion = { "Current v$it" },
        latest = "Latest DronePeak",
        released = "Released",
        size = "Size",
        changelog = "Changelog",
        noChangelog = "No changelog provided.",
        dronePeakBuildRequired = "FreeFCC upstream code updates are merged into this repo at source level. Users receive only signed DronePeak APKs.",
        upstreamApkBlocked = "Upstream APK is not installed; DronePeak APK keeps the design, icon, and language layer.",
        profileUpdateAvailable = "Optionally apply upstream DUML profile/data files only.",
        applyProfileUpdate = "Update Upstream Profiles",
        downloadDronePeakUpdate = "Download DronePeak APK",
        installDronePeakUpdate = "Install DronePeak APK",
        downloadingDronePeakUpdate = "Downloading DronePeak APK",
        applyingProfileUpdate = "Applying upstream profiles",
        profileUpdateApplied = "Profile update applied",
        checkAgain = "Check Again",
        rcPanel = "RC PANEL",
        fcc = "FCC",
        info = "Info",
        log = "Log",
        update = "Update",
        language = "Language",
        online = "ONLINE",
        offline = "OFFLINE",
        linking = "LINKING",
        error = "ERROR",
        hardwareBusy = "Hardware busy",
        fourGBusy = "4G busy",
        ledBusy = "LED busy",
        ready = "Ready",
        hardware = "Hardware",
        bootloader = "Bootloader",
        firmware = "Firmware",
        rawPayload = { "Raw payload ($it bytes):" }
    )
}
